version: '3'
services:

  db:
    restart: always
    image: ghcr.io/atsu1125/pgroonga
    shm_size: 256mb
    networks:
      - internal_network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "mastodon" , "-d", "mastodon_production"]
    volumes:
      - ./postgres:/var/lib/postgresql/data
    env_file:
      - .docker-psql.env
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"

  redis:
    restart: always
    image: redis:alpine
    networks:
      - internal_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
    volumes:
      - ./redis:/data

## PGroongaを使うからElasticSearchは要らないのだわ

  web:
    build: .
    image: atsu1125/mastodon
    restart: always
    env_file: .env.docker
    command: bash -c "rm -f /mastodon/tmp/pids/server.pid; bundle exec rails s -p 3000"
    networks:
      - external_network
      - internal_network
    healthcheck:
      test: ["CMD-SHELL", "wget -q --spider --proxy=off localhost:3000/health || exit 1"]
    ports:
      - "127.0.0.1:3000:3000"
    depends_on:
      - redis
      - db
    volumes:
      - ./public/system:/mastodon/public/system

  streaming:
    build: .
    image: atsu1125/mastodon
    restart: always
    env_file: .env.docker
    command: node ./streaming
    networks:
      - external_network
      - internal_network
    healthcheck:
      test: ["CMD-SHELL", "wget -q --spider --proxy=off localhost:4000/api/v1/streaming/health || exit 1"]
    ports:
      - "127.0.0.1:4000:4000"
    depends_on:
      - redis
      - db

  sidekiq_default:
    build: .
    image: atsu1125/mastodon
    restart: always
    env_file: .env.docker
    command: bundle exec sidekiq -q default
    depends_on:
      - redis
      - db
    networks:
      - external_network
      - internal_network
    volumes:
      - ./public/system:/mastodon/public/system
    healthcheck:
      test: ["CMD-SHELL", "ps aux | grep '[s]idekiq\ 6' || false"]

  sidekiq_push:
    build: .
    image: atsu1125/mastodon
    restart: always
    env_file: .env.docker
    command: bundle exec sidekiq -q push
    depends_on:
      - redis
      - db
    networks:
      - external_network
      - internal_network
    volumes:
      - ./public/system:/mastodon/public/system
    healthcheck:
      test: ["CMD-SHELL", "ps aux | grep '[s]idekiq\ 6' || false"]

  sidekiq_pull:
    build: .
    image: atsu1125/mastodon
    restart: always
    env_file: .env.docker
    command: bundle exec sidekiq -q pull
    depends_on:
      - redis
      - db
    networks:
      - external_network
      - internal_network
    volumes:
      - ./public/system:/mastodon/public/system
    healthcheck:
      test: ["CMD-SHELL", "ps aux | grep '[s]idekiq\ 6' || false"]

  sidekiq_mailers:
    build: .
    image: atsu1125/mastodon
    restart: always
    env_file: .env.docker
    command: bundle exec sidekiq -q mailers
    depends_on:
      - redis
      - db
    networks:
      - external_network
      - internal_network
    volumes:
      - ./public/system:/mastodon/public/system
    healthcheck:
      test: ["CMD-SHELL", "ps aux | grep '[s]idekiq\ 6' || false"]

  sidekiq_scheduler:
    build: .
    image: atsu1125/mastodon
    restart: always
    env_file: .env.docker
    command: bundle exec sidekiq -q scheduler
    depends_on:
      - redis
      - db
    networks:
      - external_network
      - internal_network
    volumes:
      - ./public/system:/mastodon/public/system
    healthcheck:
      test: ["CMD-SHELL", "ps aux | grep '[s]idekiq\ 6' || false"]

## Uncomment to enable federation with tor instances along with adding the following ENV variables
## http_proxy=http://privoxy:8118
## ALLOW_ACCESS_TO_HIDDEN_SERVICE=true
#  tor:
#    image: sirboops/tor
#    networks:
#      - external_network
#      - internal_network
#
#  privoxy:
#    image: sirboops/privoxy
#    volumes:
#      - ./priv-config:/opt/config
#    networks:
#      - external_network
#      - internal_network

networks:
  external_network:
  internal_network:
    internal: true
